name = "AlgebraCore"
uuid = "1ed6f371-fc45-4d53-9607-dafcbbd38b34"
version = "0.1.0"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
